name: CI

Read more here: https://locall.host/how-to-create-free-windows-10-rdp-vps-with-github/
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip
      - name: Unzip ngrok
        run: |
          unzip ngrok-stable-windows-amd64.zip
      - name: Connect to ngrok
        run: |
          ./ngrok.exe authtoken
          ./ngrok.exe tcp 3389
